### ISSUE TITLE
Pull in common names and aliases

### ISSUE THREAD

**Issue by jeffdc** [jeffdc/gallformers#1]
- [x] Bring the common names and aliases into the database from the CSVs
- [x] Allow the ID form to accept common names as input for host (not sure about aliases)
- [x] Display common names, when available, on the species pages and search results page

**Comment by Megachile** [comment]
I would consider common names a low priority item for galls, since they are just not widely applied. Is there a good way to import common names for plants from USDA plants or iNat? Or to import gall common names from iNat? Otherwise it's not really a github issue so much as a data entry issue.

On the host side, I definitely think enabling searching by common names is important, though, at some point.

**Comment by jeffdc** [comment]
I agree that common names are important for hosts and I want to make sure that both search and the ID screen can take common names for hosts. RE Galls, yeah not nearly as important.

**Comment by madeleineclaire** [comment]
I'm a little confused on this one. I'm looking under both Host and Genus and am not seeing common names applied consistently under the 'Host' menu and not at all under the 'Genus' menu. 

I used the following in each box:
Quercus - returned two species with common names under 'Host'. Did not display Oak in 'Genus'
Salix - no common names under 'Host', did not display Willow in 'Genus'
Rosa - No results under 'Host' or 'Genus'
Creosote - No results under 'Host' or 'Genus'

I might be ahead of myself here. Where was the source data to load the hosts and genus data pulled from? Is that still a work in progress? Sorry if I missed this somewhere.

**Comment by jeffdc** [comment]
Most of the species do not have any common names entered into the database yet. There are no common names for Genus as of yet. That is something that we will want to add. I will add a new issue for that as there is some other work related to Genus that is related.

**Comment by Megachile** [comment]
The list of hosts in the database now is just the list of species I happen to have accumulated in my personal spreadsheet last year. There are no common names added at all yet; I was under the impression this issue was about "pulling in" common names from an external source like iNat or USDA plants but since it's closed now I must have misinterpreted the intent here.

**Comment by jeffdc** [comment]
This was just about getting common names in the UI. I am not tracking data input issues etc. We can track them here if we want, but we need a new label or something for that. The idea that we discussed in another issue RE using the USDA API should be a way towards getting better data.

**Comment by madeleineclaire** [comment]
Got it. So the updates here made the site able to display both names, but another issue will track actually getting the data to pull in. Am I understanding correctly?

**Comment by jeffdc** [comment]
Generally we are not tracking data input items via issues. We could certainly do so, but if we do I recommend we add a new tag so that we can filter etc. for them.
