### ISSUE TITLE
Can't change existing host to different section

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#114]
I just renamed Quercus texana to its current name, Quercus buckleyi, and noticed it was in the white oaks for some reason. I've changed it to Lobatae 4 times now and it won't take.

**Comment by jeffdc** [comment]
Will look at this in the AM and fix it and deploy it with the other changes for undescribed that I have.

**Comment by Megachile** [comment]
Looking into this more, I think the mapping is correct, it's just showing the wrong name in the field. Eg on the Edit Host page Quercus incana shows as in section Quercus, not Lobatae, but if you edit section it is where it's supposed to be.

**Comment by jeffdc** [comment]
I fixed it but can not deploy anything as I am still stuck with this issue with the database library that I am using. We are basically dead in the water with updates until I figure this out. I have asked on the libraries discussion: https://github.com/prisma/prisma/discussions/6395 as well as in their Slack but so far have heard nothing. I need to update the library due to a bug in the library but when I do it causes this other issue which makes it so that almost all of the code that updates/deletes data no longer works. I have been trying to figure it out for 3 days with not luck. Hopefully someone will respond to that thread that I created soon. Otherwise I am not sure what to do exactly. Hooray for software.

**Comment by Megachile** [comment]
Having this issue again; just made Quercus texana (a different species from Q buckleyi, formerly Q texana :<) and tried to add it to Lobatae but it just clears the field when I submit it. This time, it doesn't seem to be adding it to the section under the hood either. I can add the species successfully on the Edit Section page tho.

**Comment by jeffdc** [comment]
Fixed with upcoming deployment
