### ISSUE TITLE
Should we add a generic "leaf" location?

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#157]
With ID of a specific observation in mind, I still think it's good that we force both admin and ID users to specify where on the leaf their gall is found. But from an organizational perspective, it's sometimes annoying that I can't filter a list of all the detachable leaf galls (eg to confirm I have everything in a given source). I guess this feels kind of hacky but I keep thinking we could make a meta-location, so the ID user could select "leaf" and it would show all results with any leaf-associated term. Thoughts?

**Comment by jeffdc** [comment]
I was thinking something similar, though I think if we just add 'leaf' to the list it will be confusing. Let me think more about a way to present this so it is clear to the user.

**Comment by madeleineclaire** [comment]
In support of this idea.

**Comment by jeffdc** [comment]
What I have come up with is this. In the ID screen there is a new `leaf (anywhere)` option in the locations filter. If this is selected, then the results will include any galls that have a location that contains the string 'leaf'. So that means:

- at leaf vein angles
- between leaf veins
- leaf edge
- leaf midrib
- lower leaf
- on leaf veins
- upper leaf

This is inclusive (OR), not exclusive (AND). 

If an additional location is chosen, say 'fruit', then to match the gall would have to have a location that is fruit AND any of the leaf locations.

**Comment by jeffdc** [comment]
The case I am still thinking about is what happens if the user selects any of the currently existing leaf locations AND the new `leaf (anywhere)` location at the same time. Currently it will just filter by that selected specific leaf location. It is silly to do since you get the same results without `leaf (anywhere)` selected. It might be confusing but it adheres to the rule that multiple selections are ANDs not ORs.

**Comment by Megachile** [comment]
That all makes sense to me; I think the inclusivity/exclusivity thing is something we would need to address in a more systematic way if we want to do that.

**Comment by madeleineclaire** [comment]
What is the benefit to the user to have the filters set up as AND over OR?

**Comment by Megachile** [comment]
If the function of the filter terms is to narrow down your options, AND filters let you do that. It lets you search for only galls that occur on the lower leaf between veins. An OR filter would show upper leaf galls on veins, midrib, etc, as well, making it harder to narrow down to the one you're looking at.
