### ISSUE TITLE
All filter terms (except host) should be multiselect

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#161]
IMO there's no reason to force users to choose only a single option in any filter category. You might be unsure if your date counts as spring or summer, or there might be multiple galls with different alignments, or a gall could have a thin wall and radiating fibers, multiple colors (base and spots), etc. Tons of reasons to allow this and none I can think of to prevent it.

**Comment by jeffdc** [comment]
I am not convinced that this is a good idea across the board. For some of the properties it seems OK but for others it is quite confusing, e.g. walls, cells, shape, texture, ... It seems doubly not useful since so many galls do not even have values for many of these properties.

**Comment by Megachile** [comment]
Hm. I have not too often found myself wishing this was changed when using the site since I made this issue. It's mostly that this is how imagined the filter terms working when I conceived them (and how they work on the iNat guides). A lot of the hickory galls specifically benefit from being able to select multiple textures. Selecting two colors lets you narrow things down if a gall is spotted or otherwise multicolored. Amphibolips galls can have both spongy and radiating walls or just one or the other, etc. I don't think it's crucial because it's rare to find a case where you get too many results after applying all the other filters, and your point about overnarrowing is definitely a good consideration. It just seems like a weird capability to lack. 

I think it's fine to leave this out for now but if and when we do a rethink/overhaul of the ID filter in bigger terms I think we should seriously consider it at least.

**Comment by jeffdc** [comment]
I agree that if we rethink the ID page we would want to revisit this.

Something that I am currently looking into is a way to make something more like the main search useful for IDing. I am going to attempt an experiment where I use the generated gall description (displayed when there is no photo) for the search index. This would mean that you type a query in that is more plain English and get back useful results sorted by relevancy. I need to figure out to handle the hosts since those are not part of the description but it would allow queries like:

- `round red cluster gall on white oak`
- `brown hairy gall on quercus stellata leaf`

My thought is that I would add it to the current ID page so you could still filter etc.

**Comment by Megachile** [comment]
It seems like a search function like that would be more useful if it included all of the source text rather than just the narrow generated description? The description is really doing nothing different than the filters already do. But I guess that's maybe a natural language UI for the filters is all you're aiming for here.

**Comment by jeffdc** [comment]
Searching the descriptions will lead to a lot of noise. To me the value in the way we extract and categorize all of the metadata from the descriptions is that it allows us to provide a better search/filter. All the generated description does is create a single collection of all the metadata without the noise. This will then create a cleaner search index. Searching descriptions can have value, but I think that should be a specific step (custom search screen or the like) someone takes rather than a generic search/ID action.

**Comment by Megachile** [comment]
> Searching the descriptions will lead to a lot of noise

Sure, but that chaos might be useful if the ID filter is coming up empty. In my mind, it doesn't seem like it would be worth the effort you're effectively using only the tags you can already filter by. But if you want to do it I have no objections.

**Comment by jeffdc** [comment]
The problem with filters is that you have to got to ID page, select a host, then click on the UI to select filter items. A text based search can be way faster. I find myself constantly wishing I had it. I want to go to the site and type into a text box like Google and get back meaningful results ranked by relevancy.

To me being able to ask the site:

`red cluster white oak petiole`

and get back a list of results (filterable - maybe just the current ID screen pre-populated) with Andricus weldi at the top is way better than the ID screen for someone that is well-versed in our data.
