### ISSUE TITLE
Global Search Research

### ISSUE THREAD

**Issue by jeffdc** [jeffdc/gallformers#17]

**Comment by jorgerasillo** [comment]
My current thought re: searching is that we should pursue algolia if we want to have fancy searching, otherwise the current search will work.

I've uploaded some sample data to a `gall` index and it has a nifty [`Generate UI Demo` for the sample data](https://www.algolia.com/realtime-search-demo/galls) 

Algolia has all sorts of UI features to let you customize how you want to work with your data, or alternatively you can use their API to do so. [Fancy vanilla js library demo](https://codesandbox.io/embed/github/algolia/doc-code-samples/tree/master/InstantSearch.js/getting-started)

The free tier includes 10 units = 10k requests which is probably enough to start with.

**Comment by jeffdc** [comment]
For now my "hack" is good enough. Will close this but later we can come back to it as we need more capacity/abilities.
