### ISSUE TITLE
Image viewer in gall page sometimes adds huge white areas

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#192]
See image; sometimes but not always (maybe something to do with aspect ratio of the image?) the image viewer (not the modal) is adding huge white areas above and below each image, pushing the source entry way down on the page. 

![image distort](https://user-images.githubusercontent.com/69063635/118407944-1d976780-b651-11eb-8d67-640b4c9c025d.PNG)

**Comment by jeffdc** [comment]
I do not see the whitespace with that species. But the reason that it happens is that one of the images is very tall, it has to scale the viewport to fit the tallest image, otherwise when you click through the images the whole page layout changes and it is very distracting and difficult to use. See for example this one: https://www.gallformers.org/gall/1092 I tried it without the predetemined size and it was much worse. It may be possible to limit the height, but that will require that the images are scaled to fit and they will, on average, be smaller.

**Comment by Megachile** [comment]
That makes sense. Could we pull the text up into the gap on the left when this happens?

**Comment by jeffdc** [comment]
I could but it would mean that the text would always be to the left of the images and not flow under it when the images are small. The challenge is that the layout is a grid and there is a limit to what is possible.

**Comment by Megachile** [comment]
Alright sounds like it's not worth addressing at the moment.
