### ISSUE TITLE
Add UI element to ID Filter to remove entries tagged "Form: Non-gall"

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#213]
The purpose of adding a non-gall filter was to be able to remove them from the ID results, but this isn't possible with the standard inclusion-only trait selection box in Advanced Filters. We would need to add a special UI item, like a checkbox, to enable this.

**Comment by jeffdc** [comment]
For ease of implementation and overall UI simplicity I did what I did with locations and added a synthetic form 'gall' so that it appears as if there is a form:gall value.

Is this sufficient?

![Screen Shot 2021-06-24 at 9 55 10 AM](https://user-images.githubusercontent.com/39919/123275582-6ead3d80-d4d2-11eb-9c81-9838926b011e.png)

**Comment by Megachile** [comment]
That approach did occur to me (get to have our cake and eat it too in terms of Form: Gall) and I think it's fine. The only reason I was leaning toward the check box is that doing it this way I think will make it much less obvious that it's an option for new users.

**Comment by jeffdc** [comment]
I would think new users would want to start out seeing all possibilities since they are possibly looking at a scale etc. The goal is to get to an ID, even if we can not tell them exactly what scale etc. if we can show them examples they can make better decisions. Based on our Slack conversation the other day I think that we ought to add caveats to pretty much all of the scales (and maybe all non-galls) that we focus on (arthropod/fungal/?) galls and we provide info RE common other gall like organisms to help with at least knowing what they are looking at it, even if we can not give a precise species/genus/family ID.

**Comment by Megachile** [comment]
> new users would want to start out seeing all possibilities

That was what I had in mind. This would be a checkbox hidden in the Advanced Filters, so it's not likely that people would overlook scales etc by accident. 

> I think that we ought to add caveats to pretty much all of the scales

This seems like a good idea. Probably worth discussing in a separate issue.

**Comment by jeffdc** [comment]
For now at least I am not going to add a new UI element. That screen is getting overly complicated as it is and adding a checkbox with a lengthy explanation of what it means to filter only galls is going to make it even more complicated. Especially since it could be in conflict with the selection made in the form filter box.
