### ISSUE TITLE
Create new system to model hybrid species

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#234]
For instance, if I find a hybrid oak, I'm not convinced that the tool will be very useful if I search the hybrid itself, since it will only show results that have been specifically reported on that hybrid (if we've even bothered, which I think we usually haven't). What I really want the tool to do is to simply combine the lists of the hybrid parents. 

_Originally posted by @Megachile in https://github.com/jeffdc/gallformers/issues/46#issuecomment-876874778_

Making a separate issue to discuss this although it obviously has implications for how we deal with a few other active issues. My proposal here would have two components. 

1. Create some kind of admin page to link the parents of a new hybrid host--the parents would need to be in the database and would be linked by searching the host list. This could just be part of the existing Host tab, something like the "undescribed" toggle on Galls but for "hybrid," which would prompt the user to fill two parent fields. 

2. When an ID user selects the hybrid, show the list of galls found on one or both parent plants. 

3. Throw up a warning that this is what we're doing and the results shouldn't be taken to indicate known relationships with the hybrid in particular.

**Comment by Megachile** [comment]
The only downsides I can think of to this approach (aside from the work to implement it) would be that there may be cases where a hybrid has a distinct gall fauna, in which case we might want to be able to manually change the results. But this is probably rare--I don't know of any cases off the top of my head--and something we could address in the ID Notes if it came to it.

**Comment by jeffdc** [comment]
My main question around this is, how important is it? I have been doing a lot of studying of oaks over the past year or so and recently have gotten to the point where I can. with a little bit of confidence know when I am seeing a possible hybrid. The main thing I have learned from hybrids, is that they seem to have a lot fewer galls. I am sure that there are counter examples to this since my data set is so small and isolated to a single genus. The other challenge I see, is that it is incredibly difficult to even ID oak hybrids (not sure about non Oaks). Is it common in other genera to have a lot of hybrids and to be able to accurately ID them?

**Comment by Megachile** [comment]
I see observations ID'd as hybrid oaks at least a few times a month (mostly in CA). I think it's not an urgent priority, but I think this is ultimately the best way to handle hybrids (rather than the way we do now) and I just brought it up in case it was something best done alongside the other taxonomic updates. If not, feel free to put it off. I did just today find myself checking two hybrid parents, though, so it's definitely not a theoretical concern.
