### ISSUE TITLE
Place field should retain contents when a species is selected

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#263]
Eg tonight I was going through the southwest galls and I will often go back and forth between selecting genus/section+place and species when the user gives one. It would be nice if I didn't have to fill in the place field again (ie it behaves the same as the other fields, not changing unless specifically altered). I realize the place field doesn't *do* anything when species is selected but that doesn't mean it needs to be cleared, does it? This is super minor but just a thought that occurred to me so np if it's tricky to do.

**Comment by Megachile** [comment]
It occurs to me that for this to be functionally complete as I was imagining it it would need to be applied to the genus field too. So eg if I'm doing southwest oak galls, I can put in the state and Quercus and add the species when I know it and unselect it when I don't without having to reenter the state and genus.

**Comment by jeffdc** [comment]
This is a bit of a challenge since the state is conveyed entirely via the URL parameters. To implement this we would need to introduce some other form of storage (cookies or the like) and change the search filtering logic to understand that not all fields should be applied in all situations as well as adding some kind of logic that would enforce species as the selection of intent vs genus if both are present. So in other words this is tricky and I would propose that we close it.

**Comment by Megachile** [comment]
I was going to say that the iNat identify tool does it this way (eg you can enter multiple taxa at once in the URL, both genus and species, and it will only show the ones that match both criteria, making the genus level redundant but still present in the URL). But I suppose that interface does often struggle to remove those correctly when selections change.
