### ISSUE TITLE
Wishlist of changes for mobile access

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#271]
This is a place to collect open-ended feedback about using the site on mobile devices. Anything that occurs to you about how the site works that is annoying, any features you think could be cool, any similar field guides you wish our site was more like, etc.

**Comment by Megachile** [comment]
Keyboard: One of my major small annoyances with using the site on my phone is that the keyboard takes up too much of the screen. This is obviously a necessary evil since there's no better way to search for host species or genus, but I think there are ways to make it less annoying. Maybe the smallest change would just be that **once I select something from the dropdown, the keyboard should automatically disappear** so I can scroll down to the next filter or to the results. A more ambitious solution might be to break the whole ID tool up into a sequence of pages like the Merlin app, so once you selected a species/genus of host, it would advance to another page of filters automatically. 

Also, if possible, I don't think the keyboard needs to come up at all for the Advanced filters. None of those have so many options that they can't be seen at once so you don't need to type it in to search for what you want. Some could even be reduced to icons?

**Comment by Megachile** [comment]
Results: The target audience for the mobile user might skew towards beginners more than the desktop site, so it might make sense to display ID results in a way that puts the most likely species first. We could use the site's built-in "Abundance" field for this but it is empty for more galls than not. Alternatively we could somehow rank them by number of iNat observations? That seems like the most direct way to get at what we want (ie how likely is an iNat user to notice this).

**Comment by jeffdc** [comment]
Some comments on each item above:

**Service Availability:** the database is not large and could be downloaded for offline use, however since this is a website and not an app it would require a re-think of how things are implemented. There are some tools that work with Chrome Desktop that allow for offline use, but I do not know what it is available (if anything) for mobile browsers. Merlin and Seek both work well offline but they are purpose built apps, one each for Android and iOS. This would probably be the best way to solve this problem but it will require at least 1 or 2 more technical volunteers that are willing to commit to create and maintain these apps.

**Location:** this is possible given that browser's offer location APIs, however the user has to grant access and it would also prepopulate on the desktop and that may become annoying very quickly. I think that this is another case where dedicated apps would solve the issue but a mobile skin of the website is not.

**Keyboard:** since the site is running in whatever mobile browser you are using it has no control over the keyboard, that is totally up to the browser. This is another one where a dedicated app would solve the issue. A mobile specific version of the ID page could be created as an alternative. It would flow differently, much as is described above, and solve various usability issues on mobile.

**Results:** I have been thinking about how we need to have a way to better rank the results. The iNat count is an interesting idea that I had not thought about before. This is feasible. We would need to integrate with the iNat API and load these counts in batch (would be too slow to query for all results every time and it would make it even harder to work in offline mode). Batching does not seem like it would be an issue given that the relative counts is all we care about. 

**Host Plant ID:** The way that the ID tool is currently implemented forces a host to be selected otherwise we will run into performance issues. I think that this issue is connected to the **Keyboard** issue in that the ID screen needs a re-write to work well on mobile. More generally I wish so much that we could have a way to help the user get to a Plant ID (family/genus) but I have not been able to come up with anything that is feasible given our constraints other than providing a link to somewhere else (like iNat).
