### ISSUE TITLE
Grey out all fields of an edit page until criteria are met to submit

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#283]
Right now eg on the Add/edit sources page it's possible to type in a title but neglect to click "add title", then fill in the rest of the fields only to realize that submit is not available because of that omission. If the site knows that an entry isn't ready to be submitted, there's no reason to let the user fill in any of the other fields either. A title should need to be selected (either selected from existing titles or added as a new one) before the other fields can be used at all.

**Comment by jeffdc** [comment]
What I have done for this is to make it so that each form will disable (gray out prevent typing in them) out all fields other than the "key" field to begin with. Once the key field is populated (e.g., gall name new or existing) then the other fields will become enabled. Fields that are required will be marked as such by having a field title that says "Field Name (required)". If all of the required fields are not populated then the Submit button will be disabled.

@megachile, does this cover what you were after?
