### ISSUE TITLE
Unable to add a plant as a gall-inducing species.

### ISSUE THREAD

**Issue by joshuac20054** [jeffdc/gallformers#312]
I have found Phoradendron macrophyllum inducing galls on Forestiera pubescens in my city, and I tried to add it to Gallformers as a gall. However when I put it filled in Phoradendron as a genus and it asked for the family, I put in Santalaceae, which is the mistletoe family, and it said "no matches found". Santalaceae is already on the site but as a host, not an inducer, so it won't let me add a member of this family as a gall inducer.

**Comment by jeffdc** [comment]
This is due to an assumption (faulty it seems) about the way Families are treated in the back-end. Basically you can not have a Family that is both a gallformer and a host. My suggestion for a workaround would be to create a new Family, Santalaceae(gall) or similar, and add the new species there. It is not perfect but I think that it should work.
