### ISSUE TITLE
How to clarify filter terms

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#62]
The glossary is nice when words appear in gall descriptions, but the most important terms to clarify are the ones in dropdown menus in each filter field. AFAIK, as part of the dropdown these can't be links to the glossary themselves, so we need some other way to offer that additional info. I suppose the simplest way to do it would be to create a separate page or subpage for each filter, with the whole list of included terms defined and labelled on figures where possible. Or maybe there's a way to do this in hover-over pop-ups so users don't have to leave the page? 

This would cover location, detachable, and any filters that (per #39) only appear for specific groups. For host we could do something like link to a list of good regional plant ID keys but there's obviously no way/reason for us to create an ID guide ourselves. The only exception is maybe oaks and hickories, which are so important for our users that it might be worth creating a short set of our own tips on how to distinguish the ones using traits most commonly visible in iNat gall observations. These could also only show up when the user has selected a host genus with such info available.

**Comment by jeffdc** [comment]
We can use the info tips that I am adding to the image admin screen on the filter/id screen to pull from the glossary and show the definitions.

I agree RE the plant ID. Some tree groups we could and should handle but generally we can not provide a plant ID database. One of my goals was to eventually work on some machine learning around Oak IDs. It is my hope that with a curated set of training data we could have a decent CV assist on IDing oaks by leaf.

**Comment by jeffdc** [comment]
For now I am going to provide simple info tips for each filter field. I will refer the user to the glossary for further info. I believe that some static pages that illustrate this stuff would be great and is something that we could link to from the glossary, and elsewhere. If someone can work up the static page content I can get them styled and deployed.

**Comment by Megachile** [comment]
I'm surprised to hear you say you were thinking of doing CV--it seems to me that iNat has covered that far better than we ever could already. 

I can write up a static page for each filter as well, and maybe we can just have the filter name link to those in the meantime?

**Comment by jeffdc** [comment]
iNat's CV is very broad and they try and tackle all species and it is pretty awesome. However, I believe that if we trained a model on, say Oak leaves, we could get better results than iNat does with Oak leaves. I think also, that we could get then better results with galls as well. We have the ability to curate a much more refined set of training data for galls and leaves (for example) than iNat does.

RE the filter description pages, sounds perfect. Once we get a template in place for the static pages you will be able to edit them and open pull requests here on Github and not have to depend on me. I am also hoping to sooner rather than later get us to the point where deployments can happen automatically as well (at least some of them).

**Comment by madeleineclaire** [comment]
I am in Southern CA and have a heck of a time with my Oak ID depending on the maturity of the oak. Especially with the shrubby White Oaks. TBH sometimes I only know what family of Oak I am looking at because of the types of galls I see on it. 

If you had CV that had more refined/focus training on Oak leaves it would be incredibly helpful, but I think that even something as simple as a simple guide showing what is what on an Oak could be sufficient for most users who may not know much about plant anatomy, but have found themselves at least involved enough in an observation to know that they are looking at a gall and have found their way to this site. 

Another thought I've had rolling around is that somewhere around the Host/Genus options on the ID page you could put a note along the lines of "Unsure of host? If you've taken photos of the host plant, iNaturalist.org can help.." and link them to the site. Something more eloquent, but it's been a long week and thats all the juice I've got haha. 

This might be a little lengthy, but I love how this guide walks through Willow ID. I've been looking for something along these lines for Oak families and if something exists that might also be sufficient as an alternative to CV: 

http://tchester.org/plants/analysis/salix/key.html

This type of simple photo was also very helpful for me in learning Willows in Southern CA:
![image](https://user-images.githubusercontent.com/77998808/106345348-5eb36980-6264-11eb-815f-7f929085f0dd.png)

**Comment by jeffdc** [comment]
The closest I have seen to that willow photo is the [Princeton Field Guide to Eastern Trees](https://press.princeton.edu/books/paperback/9780691145914/trees-of-eastern-north-america). They have winter twigs of most of the common eastern oaks and a simple leaf key. It does seem to be an under-documented thing, at least I had a hard time finding good info.
