### ISSUE TITLE
Add direct link to Map Source admin page from each gall

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#87]
This is a minor QOL feature for now but once we start adding a lot of data, I think it would be very useful. Just like the links we have now for the gall and its host relationships, I'd like a direct link to the Map Species & Sources admin page for a given gall from its public page.

**Comment by jeffdc** [comment]
My intent was to add this back when I added the other direct links, however it is not possible with the current design of the species-source mapping page as it only shows a single mapping at a time. There are at least two options:

* Rework the species-source mapping page to show all mappings for a species to a source - would need a table to display them and then edit capabilities on that (this may be possible in the future as I am adding something like that already for alias editing)
* Add a link to each row of the Source list in the Species screen (since the species-source screen needs both a species and a source to display anything)

**Comment by Megachile** [comment]
Could we just add a generic link to the species-source mapping page for the gall, leaving the source field blank? It wouldn't take you to exactly what you want to edit but it would still be an improvement over what we have now. 

Either way, not a major problem or priority for me.

**Comment by jeffdc** [comment]
Will add this one as part of today's deployment.
