### ISSUE TITLE
How to structure info from sources?

### ISSUE THREAD

**Issue by Megachile** [jeffdc/gallformers#88]
Our goal is to include all relevant info from every available source, so users can see where we got our info from and judge it for themselves. However, sources are extremely heterogeneous in format and content, and I constantly find myself waffling about what should go into an entry, or wishing the mapping UI was structured in different ways to make info more accessible. I worry about an unstructured system leading to inconsistency between different admins or even just me over time. 

I'm indecisive about the solution and would like to hear some other opinions. At this point I think I'm the only one who's spent much time trying to add data from sources, so maybe we'll need to get other people to try that out themselves and run into the same situations before we can have this conversation. 

Here are some of the big problems I've identified: 
 - Catalog-style sources include multiple entries for a species and its deprecated synonyms, each of which may have different descriptions and host lists and their own lists of older synonyms. See eg the Weld entry [here](https://www.gallformers.org/gall/742) or the Amrine entry [here](https://www.gallformers.org/gall/534).
 - Sources include many "types" of relevant information. Gall description, notes on taxonomic changes, phenology, range, category labels, figure captions, etc. What's worse is that this info is often mixed throughout the text. 
 - How do you know what is worth including? 
 - How do we achieve consistent formatting that makes this information accessible?

What do you all think? Should we leave things the way they are now and put everything in a big text box, or just do #41 and call that good, so each source will have one or more names, one or more hosts, both of which will be listed as valid/invalid and correct/incorrect as of the present, but everything else will be dumped in together. Or should we think about some more structured format? IE more than one text field per gall-source, or more than one association per gall-source to account for multiple synonyms. It would obviously be nice, for instance, if there were an easy way to see the history of taxonomic changes, or to look at all the range or phenology records at once, etc. But I'm really not sure how much of that is worthwhile or the best way to do it.

**Comment by jeffdc** [comment]
I have put some (not nearly as much as @megachile) source data etc in via the system and I think that there is real danger here of perfect being the enemy of good. I personally do not think that it is worth the effort to capture every source, every detail etc. In fact, I think that the more we add the more it confuses things for the target audience.

Putting in data will require judgement calls from the administrator that is adding the data. As an example I found some stem galls on a Pinus virginia. I googled for info and found a simple write-up. Read that and determined that it was very likely the species I found (based on data that the average person is not going to gather). I added the gallmaker to the site: https://www.gallformers.org/gall/600 and added the source that I used: https://www.gallformers.org/source/51  I did not add any other sources. I believe that the source I added is way more relevant to the average user of the site than this: https://www.biodiversitylibrary.org/item/95742#page/169/mode/1up even though the latter is the original description and naming of the species.

What I want as a user is:

* Easily find or ID a gall 
* Look at details about the gallmaker
  * basic nomenclature and taxonomic info: species, genus, family 
  * what host(s) it occurs on
  * photos
  * list of sources so I can go read more if I want to. I would not expect this list to be comprehensive as I can always google for more I want to (especially since I know the stuff in the next bullet)
  * a list of any and all known aliases (common names, former scientific names)

As a user I probably do not really care that some paper written in 1883 called the species X, I do however care that the species was at some point called X (allows me to search). If I do go read the paper from 1883 I can reasonably be expected to know to look for aliases of the species, which I conveniently have on hand thanks to the site..

I think that trying to show all of the detail of where the aliases came from etc. to the user in a cogent way is going to be quite difficult. What it maybe comes down to is:

- Is the site an education tool or a research tool? I am firmly of the belief that it is the first.

**Comment by Megachile** [comment]
Okay, I think you're right that it's worth stepping back to think about the big picture. Let me maybe make my case a bit better. I agree it's an education tool, but obviously we're all educating ourselves from publicly available materials. Its value as a tool is to skip people ahead to where we, as a community, have got to by accessing that info ourselves. If I look up some papers because I'm trying to verify and ID, I'd like to put them somewhere easier to access again next time. And if it's something particularly complex that took me a bit of time to research and draw conclusions on, I want to be able to get those conclusions quickly. Kimberlie Sasan has done a bunch of this for Texas galls, eg, and her results are scattered all over a bunch of iNat observations and private messages to me, and it wouldn't be at all convenient for me to recover that work at the moment. 

So I guess by that logic, putting 1) links to sources 2) edited quotes that extract the relevant info and 3) a write-up of any research conclusions is sufficient, and everything else I'm imagining is overkill? 

I'm not committed to doing anything else, just thought it was worth talking about.
